### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by symphorien**
This is a collection of all the fixes I had to do to build a personal project on nixos:
* overrides to build some packages  (notably a patch I submitted upstream: https://github.com/ocamllabs/ocaml-ctypes/pull/555)
* fix the build of cudf as a dependency of opam2nix
* use clasp from nixpkgs instead of the current broken derivation
* fix a shebang error
etc.
finally, lauching `gup` modified some files in the repo, I committed theses modifications.

### CODE REVIEW

**Comment by symphorien** [comment]
Ok I removed the commit about the automated update, since a build bot seems to do this automatically; this fixes the merge conflicts.

**Comment by timbertson** [comment]
Does this need an update after https://github.com/ocamllabs/ocaml-ctypes/pull/557?

**Comment by symphorien** [comment]
Well, I tried to answer your question as follows.
I went in my clone of the repo (which I hadn't touched since december), exchanged my patch with the patch corresponding to the PR.
Then I ran `gup`, which, as a side effect, updated everything from opam.
Then I tried to build my project (which I had not touched since december either).
And then, nothing built anymore.
I spent an unreasonable amount of time fixing maybe half of the dependencies of said project, up to `ctypes` to know if the patch was enough. 
(I gave up afterwards, notably llvm doesn't compile anymore)
I came up with the following patch:
```diff
diff --git a/repo/overrides/default.nix b/repo/overrides/default.nix
index ca641879..d5d1c111 100644
--- a/repo/overrides/default.nix
+++ b/repo/overrides/default.nix
@@ -34,6 +34,70 @@ in
 			configurePhase = "unset OCAMLFIND_DESTDIR";
 		}) opamPackages.gmp-xen;
 
+		optcomp = overrideAll (impl: {
+                  configurePhase = ''
+                    export OCAMLPATH="''${buildInputs// //lib:}/lib";
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    '';
+		}) opamPackages.optcomp;
+		topkg = overrideAll (impl: {
+                  configurePhase = ''
+                    export OCAML_TOPLEVEL_PATH=$(tr ' ' '\n' <<< $buildInputs | grep find)/lib/toplevel
+                    export OCAMLPATH="''${buildInputs// //lib:}/lib";
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    '';
+		}) opamPackages.topkg;
+		xmlm = overrideAll (impl: {
+                  configurePhase = ''
+                    export OCAML_TOPLEVEL_PATH=$(tr ' ' '\n' <<< $buildInputs | grep find)/lib/toplevel
+                    export OCAMLPATH="$(tr " " "\n" <<< $NIX_LDFLAGS | grep /lib | grep --  -L | tr '\n' ':' | sed -e 's/:-L/:/g' -e  's/:$//' -e 's/^-L//')";
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    echo $OCAMLPATH
+                    '';
+		}) opamPackages.xmlm;
+		integers = overrideAll (impl: {
+                  configurePhase = ''
+                    export OCAML_TOPLEVEL_PATH=$(tr ' ' '\n' <<< $buildInputs | grep find)/lib/toplevel
+                    export OCAMLPATH="$(tr " " "\n" <<< $NIX_LDFLAGS | grep /lib | grep --  -L | tr '\n' ':' | sed -e 's/:-L/:/g' -e  's/:$//' -e 's/^-L//')";
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    echo $OCAMLPATH
+                    '';
+		}) opamPackages.integers;
+		piqi = overrideAll (impl: {
+                  configurePhase = ''
+                    export OCAML_TOPLEVEL_PATH=$(tr ' ' '\n' <<< $buildInputs | grep find)/lib/toplevel
+                    export OCAMLPATH="$(tr " " "\n" <<< $NIX_LDFLAGS | grep /lib | grep --  -L | tr '\n' ':' | sed -e 's/:-L/:/g' -e  's/:$//' -e 's/^-L//')";
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    echo $OCAMLPATH
+                    '';
+		}) opamPackages.piqi;
+
+		zmq = overrideAll (impl: {
+                  configurePhase = ''
+                    export OCAMLPATH="''${buildInputs// //lib:}/lib";
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    echo $OCAMLPATH
+                    '';
+		}) opamPackages.zmq;
+
+		ulex = overrideAll (impl: {
+                  configurePhase = ''
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    '';
+		}) opamPackages.ulex;
+
+		stdint = overrideAll (impl: {
+                  configurePhase = ''
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    '';
+		}) opamPackages.stdint;
+
+		ocamlgraph = overrideAll (impl: {
+                  installPhase = ''
+                    make -d install-findlib OCAMLFINDDEST="-destdir $out/lib"
+                    '';
+		}) opamPackages.ocamlgraph;
+
 		lablgtk = overrideAll (impl: {
 			nativeBuildInputs = impl.nativeBuildInputs ++ [ pkgconfig gtk2.dev ];
 		}) opamPackages.lablgtk;
@@ -55,7 +119,17 @@ in
 
 		ctypes = overrideAll (impl: {
 			nativeBuildInputs = impl.nativeBuildInputs ++ [ pkgconfig libffi ncurses ];
-                        patches = (impl.patches or []) ++ [./install_ocaml_integers_h_once.patch];
+                  configurePhase = ''
+                    export OCAML_TOPLEVEL_PATH=$(tr ' ' '\n' <<< $buildInputs | grep find)/lib/toplevel
+                    export OCAMLPATH="$(tr " " "\n" <<< $NIX_LDFLAGS | grep /lib | grep --  -L | tr '\n' ':' | sed -e 's/:-L/:/g' -e  's/:$//' -e 's/^-L//')";
+                    export OCAMLFIND_DESTDIR=$out/lib
+                    '';
+                    patches = (impl.patches or []) ++ [
+                      #      ./install_ocaml_integers_h_once.patch
+                      (fetchpatch {url = https://github.com/ocamllabs/ocaml-ctypes/commit/55edec07708ee57f2a34ef7c8d2e1cfac345c570.patch;
+                        sha256="18aa252kdpvalpayd5i9mimzwfx7dwba0b6lr8z4jkkzcd2m41y1";
+                        name="pr557.patch";})
+                        ];
 		}) opamPackages.ctypes;
 
 		solo5-kernel-vertio = disableStackProtection opamPackages.solo5-kernel-vertio;
@@ -66,6 +140,8 @@ in
                   nativeBuildInputs = impl.nativeBuildInputs ++ [ which makeWrapper ];
                   # hack -- for some reason the makefile system ignores OCAMLPATH.
                   configurePhase = ''
+                    export OCAMLPATH="$(tr " " "\n" <<< $NIX_LDFLAGS | grep /lib | grep --  -L | tr '\n' ':' | sed -e 's/:-L/:/g' -e  's/:$//' -e 's/^-L//')";
+                    export OCAMLFIND_DESTDIR=$out/lib
                     mkdir .bin
                     makeWrapper $(which ocamlfind) .bin/ocamlfind --prefix OCAMLPATH : "$OCAMLPATH"
                     export PATH=$(readlink -f .bin):$PATH
@@ -76,6 +152,7 @@ in
                   nativeBuildInputs = impl.nativeBuildInputs ++ [ perl ];
                   configurePhase = ''
                     patchShebangs .
+                    export OCAMLFIND_DESTDIR=$out/lib
                   ''+impl.configurePhase;
                 }) opamPackages.zarith;
 
```
Outline:
environment (`OCAMLPATH`, `OCAMLFIND_DESTDIR` etc.), for some reason, is not setup anymore
propagated build inputs have no effect whatsoever, except on `NIX_LDFLAGS`
everything which uses `topkg` is deeply broken
etc.

which means that either I screwed my setup really bad, or opam2nix doesn't work anymore.

Now to the (now secondary) question of whether the PR is enough and could replace my patch:
yes the PR works, but you still have to put it in overrides since it has not been released upstream by ctypes.

**Comment by timbertson** [comment]
Hmm, sorry about that. It definitely doesn't look right that you should have to set OCAMLFIND_DESTDIR, that should be covered by https://github.com/timbertson/opam2nix-packages/blob/1e128bc85261794a52fd21cc3cf8feb8a2d08d3a/repo/overrides/ocamlfind/default.nix#L27-L40 . I'll try to look into this and figure out what's up, but unfortunately I can't promise any time soon.

**Comment by symphorien** [comment]
no worry.
Anyway, what do you want me to do regarding this PR ?

**Comment by timbertson** [comment]
If you're happy to leave it as-is then I'll hopefully get to merging it sometime, once I figure out whatever has broken in the meantime.

**Comment by symphorien** [comment]
That's fine by me :)

**Comment by timbertson** [comment]
I've had a chance to look at this now. Looks like the rampant ocamlfind breakage was caused by https://github.com/NixOS/nixpkgs/pull/26805, which I don't really understand but basically it changed the nixpkgs setup-hooks API a bit (07979a603cd69f7b9d97321fb8199f7682d18131).

So now I've cherry-picked and copy/pasted, and I believe all your fixes are on `master`. Could you give it a look / try sometime and let me know if I've missed anything? (feel free to reopen this issue if so)

**Pull request closed without merging**
